export const FETCH_FOLLOWINFO_REQUEST = 'FETCH_FOLLOWINFO_REQUEST';
export const FETCH_FOLLOWINFO_SUCCESS = 'FETCH_FOLLOWINFO_SUCCESS';
export const FETCH_FOLLOWINFO_FAILURE = 'FETCH_FOLLOWINFO_FAILURE';
