export const FETCH_FOLLOWING_REQUEST = "FETCH_FOLLOWING_REQUEST";
export const FETCH_FOLLOWING_SUCCESS = "FETCH_FOLLOWING_SUCCESS";
export const FETCH_FOLLOWING_FAILURE = "FETCH_FOWLLOWING_FAILURE";
export const FETCH_FOLLOWER_REQUEST = "FETCH_FOLLOWER_REQUEST";
export const FETCH_FOLLOWER_SUCCESS = "FETCH_FOLLOWER_SUCCESS";
export const FETCH_FOLLOWER_FAILURE = "FETCH_FOLLOWER_FAILURE";
